-- -------------------------------------------------------------
-- Supabase / PostgreSQL Database Schema for Smart Campus
-- Converted from MySQL to PostgreSQL
-- Includes Row Level Security (RLS) Policies and Sync Triggers
-- -------------------------------------------------------------

-- Enable required extensions (if not already enabled)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================================
-- 1. CREATE CUSTOM TYPES (ENUMS)
-- =============================================================
CREATE TYPE public.user_role AS ENUM ('student', 'cr', 'acr', 'teacher', 'super_admin');
CREATE TYPE public.user_status AS ENUM ('pending', 'approved', 'rejected', 'banned');
CREATE TYPE public.request_status AS ENUM ('pending', 'accepted', 'rejected');
CREATE TYPE public.section_request_status AS ENUM ('pending', 'approved', 'rejected');
CREATE TYPE public.priority_level AS ENUM ('normal', 'high', 'urgent');

-- =============================================================
-- 2. HELPER FUNCTIONS
-- =============================================================

-- Automatically update the updated_at timestamp
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- =============================================================
-- 3. CREATE TABLES
-- =============================================================

-- --------------------------------------------------------
-- Table: users (Linked to auth.users in Supabase)
-- --------------------------------------------------------
CREATE TABLE public.users (
  id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  student_id varchar(20) DEFAULT NULL,
  full_name varchar(255) NOT NULL,
  email varchar(255) UNIQUE NOT NULL,
  role public.user_role DEFAULT 'student' NOT NULL,
  department varchar(100) DEFAULT NULL,
  semester integer DEFAULT NULL,
  section varchar(50) DEFAULT NULL,
  whatsapp_number varchar(20) DEFAULT NULL,
  address text DEFAULT NULL,
  status public.user_status DEFAULT 'pending' NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- --------------------------------------------------------
-- Table: departments
-- --------------------------------------------------------
CREATE TABLE public.departments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) UNIQUE NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- --------------------------------------------------------
-- Table: activity_log
-- --------------------------------------------------------
CREATE TABLE public.activity_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.users(id) ON DELETE SET NULL,
  action varchar(255) NOT NULL,
  details text DEFAULT NULL,
  ip_address varchar(50) DEFAULT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- --------------------------------------------------------
-- Table: conversation_requests
-- --------------------------------------------------------
CREATE TABLE public.conversation_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_a uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  user_b uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  status public.request_status DEFAULT 'pending' NOT NULL,
  initiated_by uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT unique_conv UNIQUE (user_a, user_b)
);

-- --------------------------------------------------------
-- Table: cr_acr_chat
-- --------------------------------------------------------
CREATE TABLE public.cr_acr_chat (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  content text NOT NULL,
  parent_id bigint REFERENCES public.cr_acr_chat(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- --------------------------------------------------------
-- Table: deadlines
-- --------------------------------------------------------
CREATE TABLE public.deadlines (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar(255) NOT NULL,
  description text DEFAULT NULL,
  subject varchar(100) DEFAULT NULL,
  due_date timestamptz NOT NULL,
  priority public.priority_level DEFAULT 'normal' NOT NULL,
  target_department varchar(50) DEFAULT NULL,
  target_semester integer DEFAULT NULL,
  target_section varchar(20) DEFAULT NULL,
  created_by uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- --------------------------------------------------------
-- Table: deadline_links
-- --------------------------------------------------------
CREATE TABLE public.deadline_links (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deadline_id bigint REFERENCES public.deadlines(id) ON DELETE CASCADE NOT NULL,
  url varchar(500) NOT NULL,
  button_text varchar(100) DEFAULT 'Open Link' NOT NULL,
  sort_order integer DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- --------------------------------------------------------
-- Table: deadline_reads
-- --------------------------------------------------------
CREATE TABLE public.deadline_reads (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deadline_id bigint REFERENCES public.deadlines(id) ON DELETE CASCADE NOT NULL,
  user_id uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  is_acknowledged boolean DEFAULT false NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT unique_deadline_read UNIQUE (deadline_id, user_id)
);

CREATE TRIGGER update_deadline_reads_updated_at
    BEFORE UPDATE ON public.deadline_reads
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

-- --------------------------------------------------------
-- Table: discussion_posts
-- --------------------------------------------------------
CREATE TABLE public.discussion_posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section varchar(20) NOT NULL,
  department varchar(50) NOT NULL,
  user_id uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  content text NOT NULL,
  parent_id bigint REFERENCES public.discussion_posts(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- --------------------------------------------------------
-- Table: messages
-- --------------------------------------------------------
CREATE TABLE public.messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  receiver_id uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  content text NOT NULL,
  is_read boolean DEFAULT false NOT NULL,
  status public.request_status DEFAULT 'pending' NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- --------------------------------------------------------
-- Table: notices
-- --------------------------------------------------------
CREATE TABLE public.notices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  title varchar(255) NOT NULL,
  content text NOT NULL,
  target_department varchar(100) DEFAULT NULL,
  target_semester integer DEFAULT NULL,
  target_section varchar(50) DEFAULT NULL,
  external_link varchar(500) DEFAULT NULL,
  is_global boolean DEFAULT false NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- --------------------------------------------------------
-- Table: notice_links
-- --------------------------------------------------------
CREATE TABLE public.notice_links (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notice_id bigint REFERENCES public.notices(id) ON DELETE CASCADE NOT NULL,
  url varchar(500) NOT NULL,
  button_text varchar(100) DEFAULT 'Open Link' NOT NULL,
  sort_order integer DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- --------------------------------------------------------
-- Table: notice_reads
-- --------------------------------------------------------
CREATE TABLE public.notice_reads (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notice_id bigint REFERENCES public.notices(id) ON DELETE CASCADE NOT NULL,
  user_id uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  is_acknowledged boolean DEFAULT false NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT unique_notice_read UNIQUE (notice_id, user_id)
);

CREATE TRIGGER update_notice_reads_updated_at
    BEFORE UPDATE ON public.notice_reads
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

-- --------------------------------------------------------
-- Table: notifications
-- --------------------------------------------------------
CREATE TABLE public.notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  type varchar(50) DEFAULT 'general' NOT NULL,
  title varchar(255) NOT NULL,
  message text DEFAULT NULL,
  link varchar(500) DEFAULT NULL,
  is_read boolean DEFAULT false NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- --------------------------------------------------------
-- Table: section_requests
-- --------------------------------------------------------
CREATE TABLE public.section_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  from_department varchar(100) DEFAULT NULL,
  from_semester integer DEFAULT NULL,
  from_section varchar(50) DEFAULT NULL,
  to_department varchar(100) DEFAULT NULL,
  to_semester integer DEFAULT NULL,
  to_section varchar(50) DEFAULT NULL,
  requested_by uuid REFERENCES public.users(id) ON DELETE SET NULL,
  status public.section_request_status DEFAULT 'pending' NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- =============================================================
-- 4. INDEXES FOR PERFORMANCE
-- =============================================================
CREATE INDEX idx_activity_log_user_id ON public.activity_log (user_id);
CREATE INDEX idx_cr_acr_chat_user_id ON public.cr_acr_chat (user_id);
CREATE INDEX idx_deadlines_created_by ON public.deadlines (created_by);
CREATE INDEX idx_deadline_links_deadline_id ON public.deadline_links (deadline_id);
CREATE INDEX idx_deadline_reads_user_id ON public.deadline_reads (user_id);
CREATE INDEX idx_discussion_posts_user_id ON public.discussion_posts (user_id);
CREATE INDEX idx_messages_sender_receiver ON public.messages (sender_id, receiver_id);
CREATE INDEX idx_notices_sender_id ON public.notices (sender_id);
CREATE INDEX idx_notice_links_notice_id ON public.notice_links (notice_id);
CREATE INDEX idx_notice_reads_user_id ON public.notice_reads (user_id);
CREATE INDEX idx_notifications_user_id ON public.notifications (user_id);
CREATE INDEX idx_section_requests_user_id ON public.section_requests (user_id);

-- =============================================================
-- 5. AUTOMATED AUTH SYNC TRIGGER
-- =============================================================

-- This function automatically creates a new entry in the 'public.users' table
-- whenever a new user signs up through Supabase Authentication.
CREATE OR REPLACE FUNCTION public.handle_new_user_signup()
RETURNS trigger 
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.users (id, full_name, email, role, status)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'full_name', 'New Student'),
    new.email,
    'student'::public.user_role,
    'pending'::public.user_status
  );
  RETURN new;
END;
$$;

-- Trigger the handle_new_user_signup() function on new rows in auth.users
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user_signup();

-- =============================================================
-- 6. ENABLE ROW LEVEL SECURITY (RLS)
-- =============================================================
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversation_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cr_acr_chat ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.deadlines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.deadline_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.deadline_reads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.discussion_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notice_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notice_reads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.section_requests ENABLE ROW LEVEL SECURITY;

-- =============================================================
-- 7. RLS POLICIES
-- =============================================================

-- -------------------------------------------------------------
-- USERS Policies
-- -------------------------------------------------------------
-- 1. Anyone authenticated can read other users profiles (to enable messaging/discussion directory listing)
CREATE POLICY "Allow authenticated users to read user profiles"
ON public.users FOR SELECT TO authenticated
USING (true);

-- 2. Users can update their own profile
CREATE POLICY "Allow users to update their own profile"
ON public.users FOR UPDATE TO authenticated
USING (auth.uid() = id)
WITH CHECK (auth.uid() = id);

-- 3. Function to safely get user role without infinite recursion
CREATE OR REPLACE FUNCTION public.get_user_role()
RETURNS public.user_role
LANGUAGE sql
SECURITY DEFINER SET search_path = public
AS $$
  SELECT role FROM public.users WHERE id = auth.uid();
$$;

-- 4. Super admins can manage everything in the users table
CREATE POLICY "Allow admins full control over users"
ON public.users TO authenticated
USING (public.get_user_role() = 'super_admin');

-- -------------------------------------------------------------
-- DEPARTMENTS Policies
-- -------------------------------------------------------------
-- 1. Anyone authenticated can read departments
CREATE POLICY "Allow reading departments"
ON public.departments FOR SELECT TO authenticated USING (true);

-- 2. Only admins can insert/update/delete
CREATE POLICY "Admin control departments"
ON public.departments FOR ALL TO authenticated
USING (EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'super_admin'));

-- -------------------------------------------------------------
-- ACTIVITY LOG Policies
-- -------------------------------------------------------------
-- 1. Users can read their own activity logs
CREATE POLICY "Read own activity log"
ON public.activity_log FOR SELECT TO authenticated
USING (user_id = auth.uid());

-- 2. System/Admins can see everything
CREATE POLICY "Admin view activity log"
ON public.activity_log FOR SELECT TO authenticated
USING (EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'super_admin'));

-- -------------------------------------------------------------
-- CONVERSATION REQUESTS Policies
-- -------------------------------------------------------------
-- 1. View if participating
CREATE POLICY "View participating conversations"
ON public.conversation_requests FOR SELECT TO authenticated
USING (user_a = auth.uid() OR user_b = auth.uid());

-- 2. Create requests
CREATE POLICY "Create conversation request"
ON public.conversation_requests FOR INSERT TO authenticated
WITH CHECK (initiated_by = auth.uid());

-- 3. Update requests (if accepting/rejecting)
CREATE POLICY "Update conversation request"
ON public.conversation_requests FOR UPDATE TO authenticated
USING (user_a = auth.uid() OR user_b = auth.uid());

-- -------------------------------------------------------------
-- CR/ACR CHAT Policies
-- -------------------------------------------------------------
-- 1. Access restricted to CR, ACR, and Super Admins
CREATE POLICY "CR ACR Chat Access"
ON public.cr_acr_chat TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.users
    WHERE id = auth.uid() AND (role IN ('cr', 'acr', 'super_admin'))
  )
);

-- -------------------------------------------------------------
-- DEADLINES Policies
-- -------------------------------------------------------------
-- 1. Read deadlines if directed at your group, or created by you, or admin
CREATE POLICY "Select visible deadlines"
ON public.deadlines FOR SELECT TO authenticated
USING (
  created_by = auth.uid() OR
  EXISTS (
    SELECT 1 FROM public.users
    WHERE id = auth.uid() AND (
      role = 'super_admin' OR
      (
        (target_department IS NULL OR target_department = public.users.department) AND
        (target_semester IS NULL OR target_semester = public.users.semester) AND
        (target_section IS NULL OR target_section = public.users.section)
      )
    )
  )
);

-- 2. Create deadlines (only teachers, cr, acr, admin)
CREATE POLICY "Create deadlines"
ON public.deadlines FOR INSERT TO authenticated
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.users
    WHERE id = auth.uid() AND (role IN ('cr', 'acr', 'teacher', 'super_admin'))
  )
);

-- 3. Modify own deadline or admin modify
CREATE POLICY "Modify deadlines"
ON public.deadlines FOR UPDATE TO authenticated
USING (
  created_by = auth.uid() OR
  EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'super_admin')
);

-- 4. Delete own deadline or admin delete
CREATE POLICY "Delete deadlines"
ON public.deadlines FOR DELETE TO authenticated
USING (
  created_by = auth.uid() OR
  EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'super_admin')
);

-- -------------------------------------------------------------
-- DEADLINE LINKS Policies
-- -------------------------------------------------------------
-- Inherits visibility logic by checking if the parent deadline exists in accessible deadlines
CREATE POLICY "Select deadline links"
ON public.deadline_links FOR SELECT TO authenticated
USING (EXISTS (SELECT 1 FROM public.deadlines d WHERE d.id = deadline_links.deadline_id));

-- Creators/Admins can manage
CREATE POLICY "Manage deadline links"
ON public.deadline_links FOR ALL TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.deadlines d
    WHERE d.id = deadline_links.deadline_id AND (
      d.created_by = auth.uid() OR
      EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'super_admin')
    )
  )
);

-- -------------------------------------------------------------
-- DEADLINE READS Policies
-- -------------------------------------------------------------
-- 1. Read own records
CREATE POLICY "Read own deadline acknowledges"
ON public.deadline_reads FOR SELECT TO authenticated
USING (user_id = auth.uid());

-- 2. Deadline creator can view who acknowledged it
CREATE POLICY "Creator view deadline acknowledges"
ON public.deadline_reads FOR SELECT TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.deadlines d
    WHERE d.id = deadline_reads.deadline_id AND d.created_by = auth.uid()
  )
);

-- 3. Create / Update acknowledgment for oneself
CREATE POLICY "Manage own deadline acknowledgment"
ON public.deadline_reads FOR ALL TO authenticated
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

-- -------------------------------------------------------------
-- DISCUSSION POSTS Policies
-- -------------------------------------------------------------
-- 1. Read posts if in the same department/section or if admin
CREATE POLICY "Select visible posts"
ON public.discussion_posts FOR SELECT TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.users
    WHERE id = auth.uid() AND (
      role = 'super_admin' OR
      (
        public.users.department = discussion_posts.department AND
        public.users.section = discussion_posts.section
      )
    )
  )
);

-- 2. Insert new post
CREATE POLICY "Insert post"
ON public.discussion_posts FOR INSERT TO authenticated
WITH CHECK (
  user_id = auth.uid() AND
  EXISTS (
    SELECT 1 FROM public.users
    WHERE id = auth.uid() AND
    public.users.department = discussion_posts.department AND
    public.users.section = discussion_posts.section
  )
);

-- 3. Delete/Modify own post or admin
CREATE POLICY "Modify or delete own post"
ON public.discussion_posts FOR ALL TO authenticated
USING (
  user_id = auth.uid() OR
  EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'super_admin')
);

-- -------------------------------------------------------------
-- MESSAGES Policies
-- -------------------------------------------------------------
-- 1. View messages sent/received by the current user
CREATE POLICY "Select participating messages"
ON public.messages FOR SELECT TO authenticated
USING (sender_id = auth.uid() OR receiver_id = auth.uid());

-- 2. Insert message as current user
CREATE POLICY "Insert messages"
ON public.messages FOR INSERT TO authenticated
WITH CHECK (sender_id = auth.uid());

-- 3. Update own messages (e.g. receiver marking as read)
CREATE POLICY "Update participating messages"
ON public.messages FOR UPDATE TO authenticated
USING (sender_id = auth.uid() OR receiver_id = auth.uid());

-- -------------------------------------------------------------
-- NOTICES Policies
-- -------------------------------------------------------------
-- 1. Read notice if global, directed at your group, or admin/creator
CREATE POLICY "Select visible notices"
ON public.notices FOR SELECT TO authenticated
USING (
  is_global = true OR
  sender_id = auth.uid() OR
  EXISTS (
    SELECT 1 FROM public.users
    WHERE id = auth.uid() AND (
      role = 'super_admin' OR
      (
        (target_department IS NULL OR target_department = public.users.department) AND
        (target_semester IS NULL OR target_semester = public.users.semester) AND
        (target_section IS NULL OR target_section = public.users.section)
      )
    )
  )
);

-- 2. Create notices (restricted roles)
CREATE POLICY "Insert notices"
ON public.notices FOR INSERT TO authenticated
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.users
    WHERE id = auth.uid() AND (role IN ('cr', 'acr', 'teacher', 'super_admin'))
  )
);

-- 3. Modify/Delete notices (creator or admin)
CREATE POLICY "Manage notices"
ON public.notices FOR ALL TO authenticated
USING (
  sender_id = auth.uid() OR
  EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'super_admin')
);

-- -------------------------------------------------------------
-- NOTICE LINKS Policies
-- -------------------------------------------------------------
CREATE POLICY "Select notice links"
ON public.notice_links FOR SELECT TO authenticated
USING (EXISTS (SELECT 1 FROM public.notices n WHERE n.id = notice_links.notice_id));

CREATE POLICY "Manage notice links"
ON public.notice_links FOR ALL TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.notices n
    WHERE n.id = notice_links.notice_id AND (
      n.sender_id = auth.uid() OR
      EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'super_admin')
    )
  )
);

-- -------------------------------------------------------------
-- NOTICE READS Policies
-- -------------------------------------------------------------
CREATE POLICY "Read own notice acknowledges"
ON public.notice_reads FOR SELECT TO authenticated
USING (user_id = auth.uid());

CREATE POLICY "Creator view notice acknowledges"
ON public.notice_reads FOR SELECT TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.notices n
    WHERE n.id = notice_reads.notice_id AND n.sender_id = auth.uid()
  )
);

CREATE POLICY "Manage own notice acknowledgment"
ON public.notice_reads FOR ALL TO authenticated
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

-- -------------------------------------------------------------
-- NOTIFICATIONS Policies
-- -------------------------------------------------------------
-- 1. Select own notifications only
CREATE POLICY "Select own notifications"
ON public.notifications FOR SELECT TO authenticated
USING (user_id = auth.uid());

-- 2. Update own notifications
CREATE POLICY "Update own notifications"
ON public.notifications FOR UPDATE TO authenticated
USING (user_id = auth.uid());

-- -------------------------------------------------------------
-- SECTION REQUESTS Policies
-- -------------------------------------------------------------
-- 1. View if participating
CREATE POLICY "Select participating section requests"
ON public.section_requests FOR SELECT TO authenticated
USING (
  user_id = auth.uid() OR
  requested_by = auth.uid() OR
  EXISTS (
    SELECT 1 FROM public.users
    WHERE id = auth.uid() AND (role IN ('cr', 'acr', 'super_admin'))
  )
);

-- 2. Create section request
CREATE POLICY "Insert section requests"
ON public.section_requests FOR INSERT TO authenticated
WITH CHECK (user_id = auth.uid());

-- 3. Handle/Process requests (Admins, CRs, ACRs)
CREATE POLICY "Update section requests"
ON public.section_requests FOR UPDATE TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.users
    WHERE id = auth.uid() AND (role IN ('cr', 'acr', 'super_admin'))
  )
);
